# Generated by Django 4.2.27 on 2025-12-26 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_min', models.IntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='verde', max_length=20)),
                ('status', models.CharField(default='todo', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.project')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='spaces.space')),
            ],
        ),
    ]
