# Generated by Django 4.2.27 on 2025-12-26 23:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
